apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.20
        imagePullPolicy: IfNotPresent
        name: backend
        env:
          - name: HTTP_PORT
            value: "9000"
          - name: postgresql-db
            value: "5432"
