apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: multitool
  name: frontend-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
    spec:   
      containers:   
      - image: nginx:1.20   
        imagePullPolicy: IfNotPresent   
        name: frontend   
      - image: praqma/network-multitool:alpine-extra   
        imagePullPolicy: IfNotPresent   
        name: backend   
        env:   
          - name: HTTP_PORT   
            value: "8080"      
