image: docker:20.10.5
services:
  - docker:20.10.5-dind
stages:
  - build
  - deploy

before_script:
  - echo $CI_REGISTRY_USER
  - echo $CI_COMMIT_REF_NAME
  - docker login --username dmitrykraska --password $DOCKER_PASSWORD
  
build:
  stage: build
  script:
    - docker login --username dmitrykraska --password $DOCKER_PASSWORD    
    - docker build -t dmitrykraska/diplomnetology:latest .
    - docker push dmitrykraska/diplomnetology:latest  
  only:
    - main
build&deploy:
  stage: deploy
  script:
    - docker login --username dmitrykraska --password $DOCKER_PASSWORD
    - docker build -t dmitrykraska/diplomnetology:$CI_COMMIT_REF_NAME .
    - docker push dmitrykraska/diplomnetology:$CI_COMMIT_REF_NAME
  only:
    - tags


