apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-app
  name: nginx-my
  namespace: default
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 32000
  selector:
    app: my-app
